### ISSUE TITLE
コンテキストメニューの表示

### ISSUE THREAD

**Issue by kingtosh** [tksugimoto/chrome-extension_show-menu-by-text-selection#3]
テキスト選択時にコンテキストメーニュー全体を表示することはできませんでしょうか？

**Comment by tksugimoto** [comment]
以下、`コンテキストメニュー` = `右クリックしたときにでるChromeが用意するメニュー（戻る・進む・再読み込み・名前をつけて保存など）`として話を進めます。

Chrome拡張でもコンテキストメニューをユーザーによる右クリック以外の手段で動的に表示させることはできないと思われます。
このChrome拡張のように選択時に独自メニューを表示させることはできますが、Chromeのコンテキストメニューの機能をすべてコピーすることは技術的にできません。

なお、Chrome拡張に[chrome.contextMenus](https://developer.chrome.com/extensions/contextMenus "https://developer.chrome.com/extensions/contextMenus") APIはありますが、これは右クリックして表示されたコンテキストメニューに拡張単位に独自のメニューを追加するだけ機能で、コンテキストメニュー自体の表示はできません。

**Comment by kingtosh** [comment]
ご返信ありがとうございます。
色々探してみても、そういうものが全然見つからないのは、そういうわけだったんですね。
